### ISSUE TITLE
Larger demo application

### ISSUE THREAD

**Issue by cpursley** [charypar/reflex-talk#2]
Arch is the most compelling approach to building isomorphic web applications that I've come across. Are there plans to provide a larger example application? I think this would increase adoption of Arch. What I have in mind is an example Arch client a with a backing server that has the following features:
1. Basic Authentication & Authorization
2. A few data models with associated models
3. Nested routes based on model associations

Perhaps expanding on this existing arch-talk demo where search results can be saved and belong to a user. Something like that. Anyways, Arch is a very well done framework and LiveScript is a great decision. Plus, the documentation is good for such a young project.

**Comment by cpursley** [comment]
Also, maybe there's some common example React applications that can be written in the _Arch_ style. Feel free to close this if it's not a direction you're interesting in going, as it's not really an issue per se. Just throwing some ideas out there.

**Comment by charypar** [comment]
For posterity: There is now an issue on the main project for discussing example code ideas, see arch-js/arch#69

Sorry @cpursley for not getting back on this, but I see you found the issue :)

**Comment by cpursley** [comment]
Yep, saw that - thanks!
